apiVersion: v1
kind: Namespace
metadata:
  name: ingress
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress
  namespace: ingress
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 3.21.0
