apiVersion: v1
kind: Namespace
metadata:
  name: falco
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: falco
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: falco
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/falco
    directory:
      recurse: true
    repoURL: https://github.com/ams0/argocd-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
