apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/helm-operator
    directory:
      recurse: true
    repoURL: https://github.com/ams0/argocd-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
