apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: infra
  source:
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
          - vault.ingress.stackmasters.com
          tls:
          - secretName: vault-ssl
            hosts:
            - vault.ingress.stackmasters.com
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
        unsealer:
          image:
            repository: ghcr.io/banzaicloud/bank-vaults
          args:
            [
              "--mode",
              "k8s",
              "--k8s-secret-namespace",
              "vault",
              "--k8s-secret-name",
              "vault-tls",
            ]
        vault:
          externalConfig:
            auth:
              - type: kubernetes
                roles:
                  # Allow pod in the vault namespace that use the vault SA to use the secret kv store
                  - name: default
                    bound_service_account_names: vault
                    bound_service_account_namespaces: vault
                    policies: allow_secrets
                    ttl: 1h
            policies:
              - name: allow_secrets
                rules: path "secret/*" {
                  capabilities = ["create", "read", "update", "delete", "list"]
                  }
              - name: allow_pki
                rules: path "pki/*" {
                  capabilities = ["create", "read", "update", "delete", "list"]
                  }
          envSecrets:
          - secretName: mysql
            secretKey: mysql-password
            envName: MYSQL_PASSWORD
            config:
              storage:
                mysql:
                  address=vaultql.mysql.database.azure.com:3306
                  username=vault
                  mysql.password="[[.Env.MYSQL_PASSWORD]]"
          replicaCount: 2
    path: charts/vault/
    repoURL: https://github.com/banzaicloud/bank-vaults
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
